table 'DAX Format'
	lineageTag: ed5390f2-8a5b-4abb-92be-c7810eb5425f

	measure CF_MinMax_TotalEmployees = ```
			
			VAR _TotalEmployees = [Total Employees]
			VAR _Max = 
			MAXX(
			    ALLSELECTED(Dim_HiredDate[Year]),
			    [Total Employees]
			)
			VAR _Min = 
			MINX(    
			    ALLSELECTED(Dim_HiredDate[Year]),
			    [Total Employees]
			)
			VAR Result = 
			SWITCH(
			    TRUE(),
			    _TotalEmployees = _Max, "GREEN",
			    _TotalEmployees = _Min, "RED",
			    "#FFFFFF00"
			    )
			RETURN
			Result
			```
		lineageTag: c1a5d62a-4c5e-4a22-b243-b9ee69af61ef

	measure CF_MinMax_TerminatedEmployees = ```
			
			VAR _TermitedEmployees = [Terminated Employees]
			VAR _Max = 
			MAXX(
			    ALLSELECTED(Dim_TermDate[Year]),
			    [Terminated Employees]
			)
			VAR _Min = 
			MINX(    
			    ALLSELECTED(Dim_TermDate[Year]),
			    [Terminated Employees]
			)
			VAR Result = 
			SWITCH(
			    TRUE(),
			    _TermitedEmployees = _Max, "GREEN",
			    _TermitedEmployees = _Min, "RED",
			    "#FFFFFF00"
			    )
			RETURN
			Result
			```
		lineageTag: d5d87e06-7aa2-4c40-9e38-89bbca6fec78

	measure CF_SubTitle_HiredEmployees =
			
			VAR _TotalEmployees = [Total Employees]
			VAR Result = FORMAT(_TotalEmployees, "0")
			RETURN
			Result
		lineageTag: d2c2778f-1111-44f3-bde8-b28e6c65556c

	measure CF_SubTitle_TerminatedEmployees =
			
			VAR _TerminatedEmployees = [Terminated Employees]
			VAR Result = FORMAT(_TerminatedEmployees, "0")
			RETURN
			Result
		lineageTag: d4da1b51-7b2d-4e53-b824-52da67c31e2a

	measure CF_Label_ActiveEmployees = ```
			
			VAR _SingleActive = [Active Employees]
			VAR _TotalActive = 
			CALCULATE(
			    [Active Employees],
			    ALL(Dim_Location[HQ Vs Branches]
			    )
			)
			VAR _pctActive = DIVIDE(_SingleActive, _TotalActive)
			VAR Result = FORMAT(_SingleActive, "0") & " (" & FORMAT(_pctActive, "0%") & ")"
			RETURN
			Result
			```
		lineageTag: 1fadf085-67b8-4b6b-8260-500a44715f7d

	measure CF_ReportOwner = "Produced by Diane FOKOUA"
		lineageTag: 5674e37b-6f4d-4bc2-9cc7-19a6984e7918

	measure Cf_LastRefreshDate =
			
			VAR _LastDatetimeRefresh = MAX('Last Date Refresh'[Last Date Refresh])
			VAR Result = "Last Refresh Date: " & FORMAT(_LastDatetimeRefresh, "dd/mm/yyyy")
			RETURN
			Result
		lineageTag: 8af4068e-8db9-405f-9a8e-8a20ae5d5cb5

	column Column
		isHidden
		formatString: 0
		lineageTag: db573a09-5467-4d4f-ac22-e24483b81038
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition 'DAX Format' = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 3bc7c77a85674e6ba74c46e8837a09c9

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

